[book]
authors = ["Franz Dietrich"]
language = "de"
multilingual = false
src = "src"
title = "Pythonanleitung"

[build]
create-missing = false
build-dir = "book"

[preprocessor.links]

[output.html.fold]
enable = true

#[output.epub]

#[output.latex]
#command = "/home/dietrich/Projekte/Source/mdbooklatex/target/debug/mdbook-latex"
#latex    = true  # default = true
#pdf      = true  # default = false
#markdown = true  # default = false
